### ISSUE TITLE
    control=opt.Training['control']).cuda() 

### ISSUE THREAD

**Issue by c1a1o1** [CompVis/image2video-synthesis-using-cINNs#3]
F:\ProgramData\Anaconda3\python.exe F:/work/mingxingshipin/test/image2video-synthesis-using-cINNs-main/generate_samples.py
Traceback (most recent call last):
  File "F:/work/mingxingshipin/test/image2video-synthesis-using-cINNs-main/generate_samples.py", line 32, in <module>
    model = Model(ckpt_path, args.seq_length)
  File "F:\work\mingxingshipin\test\image2video-synthesis-using-cINNs-main\get_model.py", line 42, in __init__
    control=opt.Training['control']).cuda()
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 373, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 367, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "F:\ProgramData\Anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigKeyError: Missing key control
    full_key: Training.control
    object_type=dict

Process finished with exit code 1

**Comment by mdorkenw** [comment]
Hi! 

Thanks for your interest in our work and thanks for sharing this error. Indeed, I forget to set the 'control' key in the config files. This key indicates if the cINN is conditioned on an additional 'controling' factor which is often false except for special cases e.g. BAIR.

I reuploaded the pre-trained models with now the correct configs. Please let me know if the problem still occurs, otherwise, I am closing this issue :)
